export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const ADD_NEW_PHOTO_SUCCESS = 'ADD_NEW_PHOTO_SUCCESS';
export const ADD_NEW_PHOTO_REQUEST = 'ADD_NEW_PHOTO_REQUEST';
export const ADD_NEW_PHOTO_ERROR = 'ADD_NEW_PHOTO_ERROR';

export const GET_GALLERY_USER_SUCCESS = 'GET_GALLERY_USER_SUCCESS';
export const GET_GALLERY_USER_REQUEST = 'GET_GALLERY_USER_REQUEST';
export const GET_GALLERY_USER_ERROR = 'GET_GALLERY_USER_ERROR';

export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';
export const DELETE_PHOTO_ERROR = 'DELETE_PHOTO_ERROR';

export const GET_ALL_PHOTO_SUCCESS = 'GET_ALL_PHOTO_SUCCESS';
export const GET_ALL_PHOTO_REQUEST = 'GET_ALL_PHOTO_REQUEST';
export const GET_ALL_PHOTO_ERROR = 'GET_ALL_PHOTO_ERROR';


export const GET_GALLERY_BY_SUCCESS = 'GET_GALLERY_BY_SUCCESS';
export const GET_GALLERY_BY_REQUEST = 'GET_GALLERY_BY_REQUEST';
export const GET_GALLERY_BY_ERROR = 'GET_GALLERY_BY_ERROR';